### ISSUE TITLE
Windows Services under .NET Core 2.1

### ISSUE THREAD

**Issue by TimurZanagar** [Topshelf/Topshelf#455] opened 2018-06-12 14:44 UTC
Hi folks,

I just read the article "[Hidden Gems in .NET Core 2.1](https://www.hanselman.com/blog/ASPNETCoreArchitectDavidFowlersHiddenGemsIn21.aspx)" and there are some gems which should help you to migrate Topshelf to .NET Core.

Why? Microsoft released an interface called IHostingService which is packed in the [NuGet](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.WindowsServices/). 

I don't know if this is really useful, but I wanted to leave this information here for the issues:
#https://github.com/Topshelf/Topshelf/issues/444
#https://github.com/Topshelf/Topshelf/issues/393
#https://github.com/Topshelf/Topshelf/issues/277 

Here are some further links:
- [Documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&tabs=aspnetcore2x)
- [Samples](https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples/2.x)

**Comment by phatboyg** [comment] 2018-06-12 18:34
Thanks. The develop branch already works with .NET core, support for `IHostedService` might make sense at some point, just to make it easy to move services from running within ASP.NET to Topshelf.

There is also at some point likely synergy between Topshelf and the Generic ASP.NET Host effort.

**Comment by RedDeathGitHub** [comment] 2018-08-07 11:33
Do you have a timeline when a stable version, working under .NET Core 2.1, will be released?

**Comment by MartinPettit** [comment] 2018-09-03 14:32
I would also be keen to know when this .NET Core-compatible version will be released

**Comment by phatboyg** [comment] 2018-09-18 20:32
The prerelease packages are available now for testing. once verified, they'll be released. You can help here :)

**Comment by china-live** [comment] 2018-09-19 08:34
加油！

**Comment by Nekromancer** [comment] 2018-09-19 08:38
Working great on Windows Server 2016 with .NET Core 2.1 Self-Contained app. Thanks!

**Comment by drano** [comment] 2018-09-27 20:00
How to implement it with .NET Core 2.1 ? Could you provide an example ?

**Comment by Nekromancer** [comment] 2018-09-27 20:05
Just use it exactly like in the .NET Framework. Start with console app and build TopShelf as in documentation. Nothing weird here

**Comment by drano** [comment] 2018-09-27 21:28
My console app is working, but I cannot install it as a windows service. I have an error message
"Error 1053: The service did not respond to the start or control request in a timely fashion."

**Comment by Nekromancer** [comment] 2018-09-27 21:31
Are you using latest preview nuget? Show some code so we can help

**Comment by drano** [comment] 2018-09-27 21:37
Version: 4.1.0.175-Desktop
.NET Core: 2.1
      
```
using System;
using Topshelf;
using Topshelf.HostConfigurators;

namespace ConsoleApp1
{
    class MyService : ServiceControl
    {
        public bool Start(HostControl hostControl)
        {
            Console.WriteLine("Start");
            return true;
        }

        public bool Stop(HostControl hostControl)
        {
            Console.WriteLine("Stop");
            return true;
        }
    }

    class Program
    {
        public static void Main(string[] args)
        {
          
            var host = HostFactory.New(x =>
            {
                x.Service<MyService>();

                ConfigureService(x, "MyServices");
            });

            host.Run();
        }

        private static void ConfigureService(HostConfigurator x, string serviceName)
        {
            x.StartAutomatically();
            x.SetDisplayName(serviceName);
            x.SetServiceName(serviceName);

            x.RunAsPrompt();

            //x.UseNLog();

            x.EnableServiceRecovery(r =>
            {
                r.RestartService(0);
                r.OnCrashOnly();
                r.SetResetPeriod(1);
            });
        }
    }
}
```

**Comment by phatboyg** [comment] 2018-09-27 21:49
You realize it's GA now, right? No need for a preview.

**Comment by drano** [comment] 2018-09-27 22:42
I don’t understand. What’s mean « GA » ? My previous code is in .net core. Is it correct ?

**Comment by chrkon** [comment] 2018-09-28 11:48
Take a look to your code. There is a line with "run as prompt".I think this could be the reason.A service is running in the background without a command line interface. Running as prompt will start the service as a console programm.ChristofAm 28.09.2018 12:42 vorm. schrieb Didier Rano <notifications@github.com>:I don’t understand. What’s mean « GA » ? My previous code is in .net core. Is it correct ?

**Comment by Nekromancer** [comment] 2018-09-28 12:45
RunAsPrompt is helper function for topshelf to ask for account during service install. It has nothing to do with starting a service as command line. For me your code seems fine. It's working for me. Are you publishing it to self-contained package?

**Comment by drano** [comment] 2018-09-28 13:35
Yes, I am using a self-contained package.

When I try to install with "myservice.exe install" , then I have an error message
"An exception occurred during the Install phase.
System.PlatformNotSupportedException: Operation is not supported on this platform."

When I try to install with "sc.exe create binpath="fullpath\myservice.exe", then I start this service, I have the exception
"Error 1053: The service did not respond to the start or control request in a timely fashion."

**Comment by Nekromancer** [comment] 2018-09-28 17:40
What operating system are you using? Can you reproduce this on another machine?

**Comment by drano** [comment] 2018-09-28 20:10
On Windows Server 2012R2... Old version !
But, same problem with Windows server 2016

**Comment by sphiecoh** [comment] 2018-10-11 00:00
I am getting the same exception on windows server 2016

**Comment by fabricioferreira** [comment] 2018-10-19 14:42
Same exception on Windows 10.

**Comment by paddydev** [comment] 2018-11-08 07:00
> Version: 4.1.0.175-Desktop
> .NET Core: 2.1
> 
> ```
> using System;
> using Topshelf;
> using Topshelf.HostConfigurators;
> 
> namespace ConsoleApp1
> {
>     class MyService : ServiceControl
>     {
>         public bool Start(HostControl hostControl)
>         {
>             Console.WriteLine("Start");
>             return true;
>         }
> 
>         public bool Stop(HostControl hostControl)
>         {
>             Console.WriteLine("Stop");
>             return true;
>         }
>     }
> 
>     class Program
>     {
>         public static void Main(string[] args)
>         {
>           
>             var host = HostFactory.New(x =>
>             {
>                 x.Service<MyService>();
> 
>                 ConfigureService(x, "MyServices");
>             });
> 
>             host.Run();
>         }
> 
>         private static void ConfigureService(HostConfigurator x, string serviceName)
>         {
>             x.StartAutomatically();
>             x.SetDisplayName(serviceName);
>             x.SetServiceName(serviceName);
> 
>             x.RunAsPrompt();
> 
>             //x.UseNLog();
> 
>             x.EnableServiceRecovery(r =>
>             {
>                 r.RestartService(0);
>                 r.OnCrashOnly();
>                 r.SetResetPeriod(1);
>             });
>         }
>     }
> }
> ```
Able to install .net core 2.1 console app as windows service . But when i try to configure Log4net using Topshelf Log4net extension nuget and call UseLog4Net using hostconfigurator, I see the files created but not writing any logs when I run as a service. But the same works fine  if i run it in local.  Any help is appreciated. Thanks !

**Comment by snakefoot** [comment] 2018-11-08 19:13
@paddydev Sounds similar to this: https://stackoverflow.com/questions/50746454/why-is-my-windows-service-not-logging-until-the-service-is-restarted

**Comment by boekabart** [comment] 2018-11-26 20:08
I'd like to confirm here that using TopShelf 4.1.0  'GA' release, I was able to target my application to netcoreapp1.1 - runtime win7-x64, and install and run it as a service, under both Windows 10 pro, as well as windows 2008R2  x64 (which doesn't even have .net 4.5.2 installed).

The only thing I had to do is specify on the command line to install as something, as our application's default is to use the popup. I didn't have to remove the `RunAsPrompt` code that makes that the default! 

Only suggestion I would have, is to maybe remove this RunAsPrompt from the public API for the non net4xx builds, as it will crash anyway. It forces you, as an app developer, to at least realise this when targeting netcoreapp.

**Comment by mtherien** [comment] 2018-12-13 16:51
I am also getting this error.  TopShelf 4.1.0, target app netcoreapp2.1, runtime win10-x64.

I do not have the RunAsPrompt in my code.

This is a simple service that starts a Quartz.net process.

I have tried using sc.exe to manually create the service, and get the same error.

"Error 1053: The service did not respond to the start or control request in a timely fashion." seems to occur immediately after starting the service.  The Event Logs do not have any events recorded.

Any help anyone could provide would be appreciated.

**Comment by mjsiers** [comment] 2018-12-19 20:01
I am also seeing this error using TopShelf 4.1.0 with .netcoreapp2.1 on win10-x64.
Any new ideas on how to get around this issue?

**Comment by mjsiers** [comment] 2018-12-19 20:45
Here is the Serilog output when starting on the command line.

[14:40:55 INF] Topshelf v4.1.0.172, .NET Framework v4.0.30319.42000
[14:40:57 ERR] The service failed to start.
System.InvalidOperationException: Cannot start service Agent on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

**Comment by mjsiers** [comment] 2018-12-21 16:52
I was able to get this working and even upgraded my app to .netcoreapp2.2.  

The issue was that I was doing too much work before the service started and this was causing the timeout error.  My solution was to move all my initialization code into a background thread to reduce the service startup time.

**Comment by codermrrob** [comment] 2018-12-30 13:07
I get the same issue...

```
[15:05:40 DBG] Starting Emailer service
[15:05:42 ERR] The service failed to start.
System.InvalidOperationException: Cannot start service Emailer service on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()
```


.net core 2.1
Windows Server 2016/Win 10 Pro
TopShelf 4.1.0 (and 4.1.0.180)
Runtime win10-x64
Published as a Self-contained app.

As far as I can see everything should be OK. Code is basically the same as it usually is.
```
            HostFactory.New(tsc =>
            {

                int syslogPort = Convert.ToInt32(appSettings["SyslogPort"]);
                Log.Logger = new LoggerConfiguration()
                    .ReadFrom.Configuration(appSettings)
                    .WriteTo.Console(theme: AnsiConsoleTheme.Code)
                    .WriteTo.Syslog("localhost", syslogPort, "Email Service", outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] {Message} {Properties} {Exception}")
                    .CreateLogger();

                tsc.UseAutofacContainer(_container);

                tsc.Service<EmailService>(svc =>
                {
                    svc.ConstructUsingAutofacContainer();
                    svc.WhenStarted((service, hostControl) => service.Start(hostControl));
                    svc.WhenStopped((service, hostControl) => service.Stop(hostControl));
                });

                tsc.SetStartTimeout(TimeSpan.FromSeconds(20));
                tsc.SetStopTimeout(TimeSpan.FromSeconds(20));

                tsc.EnableShutdown();
                tsc.SetServiceName(appSettings["ServiceName"]);
                tsc.SetDisplayName(appSettings["DisplayName"]);
                tsc.SetDescription(appSettings["Description"]);
                tsc.UseSerilog();
                tsc.RunAsNetworkService();
            });
```

The service itself is just starting up MassTransit, nothing unusual in it. And of course it runs fine in console mode. I don't think this is a time out issue so long as the `SetStartTimeout` works as I expect it to.

**Comment by lugerf** [comment] 2019-02-24 11:47
I experienced the same issue where 

1. The installation failed by `<TargetExecutable>.exe install` and
2. Manual registration by `sc.exe` of SysWOW64 worked, but resulted in error 1053 on service startup. 
  
=> I could resolve it by changing my `<RuntimeIdentifier>` from `win-x64` to `win-x86`. After the service installation  (self-contained app on .net core 2.2) everything worked fine.

Could anyone explain to me, why `win-x64` did not work?

**Comment by codermrrob** [comment] 2019-02-24 12:48
nice tip, but had a quick look at work around but no joy with it yet. No time to look at it deeper again until the end of next week. But will try again then and report back.

Perhaps in the meantime you could post your `HostFactory` config code and your `PropertyGroup` config from the project file, for comparison? Maybe I am doing something silly and missing it.
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
```
I've been using  `NSSM` to at least get the services installed but its not exactly an ideal solution :/

**Comment by kht321** [comment] 2019-06-12 03:34
> I was able to get this working and even upgraded my app to .netcoreapp2.2.
> 
> The issue was that I was doing too much work before the service started and this was causing the timeout error. My solution was to move all my initialization code into a background thread to reduce the service startup time.

Ye

> I was able to get this working and even upgraded my app to .netcoreapp2.2.
> 
> The issue was that I was doing too much work before the service started and this was causing the timeout error. My solution was to move all my initialization code into a background thread to reduce the service startup time.

Yes, i also got the same issue. And then fixed by created a background thread.

My solution is referenced from #183  [Topshlef 3.1.107.0 Service not starting only on windows server 2012 ](https://github.com/Topshelf/Topshelf/issues/183)

**Comment by shuk** [comment] 2019-07-19 13:29
I had the same issue (Error 1053) with .NET Core 2.2 self-contained (*.exe) and topshelf-based windows service which had been registered with "sc create" command. I don't know why, but the issue has disappeared after the deletion of the following row from my code: "x.SetServiceName(serviceName)".

**Comment by bilalmalik777** [comment] 2019-12-25 13:00
How to add different services as depeendency injection in topshelf? Actually it is throwing error when try to communicate with db

**Comment by faze79** [comment] 2020-02-14 12:53
I have the same issue with .NET Core 2.2 self-contained (*.exe) and topshelf-based windows service.

Topshelf v4.2.1.215, .NET Framework v4.0.30319.42000
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service xxx on computer '.'. ---> System.ComponentModel.Win32Exception: Il servizio non ha risposto alla richiesta di avvio o controllo nel tempo previsto
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

**Comment by oleksabor** [comment] 2020-04-30 11:14
I have got something weird today.
There is .exe built for .NET Core 2.2 

It was installed on the Windows Service 2016 (Azure virtual machine) at 22 Jan 2020 using the `.exe install` option

It was installed like a charm and is working until now.

I've just tried today to start the VM and install one more service instance. 
However the problem is that it fails to be installed with the platform not supported error

```
[1] 2020-04-30 10:57:01.6082 Info (Topshelf.HostFactory) Configuration Result:
[Success] Name MessageClient
[Success] ServiceName MessageClient
[1] 2020-04-30 10:57:01.6840 Info (Topshelf.HostConfigurators.HostConfiguratorImpl) Topshelf v4.2.1.215, .NET Framework v4.0.30319.42000
[1] 2020-04-30 10:57:01.7118 Debug (Topshelf.Hosts.InstallHost) Attempting to install 'MessageClient'
[1] 2020-04-30 10:57:01.7530 Info (Topshelf.Runtime.Windows.HostInstaller) Installing MessageClient service
[1] 2020-04-30 10:57:01.8315 Error (Topshelf.HostFactory) The service terminated abnormally
	[InvalidOperationException] The installation failed, and the rollback has been performed.
		at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
		at Topshelf.Runtime.Windows.WindowsHostEnvironment.InstallService(InstallHostSettings settings, Action`1 beforeInstall, Action afterInstall, Action beforeRollback, Action afterRollback)
		at Topshelf.Hosts.InstallHost.Run()
		at Topshelf.HostFactory.Run(Action`1 configureCallback)
	[PlatformNotSupportedException] Operation is not supported on this platform.
		at System.ServiceProcess.ServiceProcessInstaller.GetLoginInfo()
		at System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
		at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
		at Topshelf.Runtime.Windows.HostInstaller.Install(IDictionary stateSaver)
		at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
		at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
```

It looks like `ServiceProcessInstaller.GetLoginInfo()` is raising the `PlatformNotSupportedException`

The most strange is that I'm using the same binaries (and the same VM instance) that were working fine on 22 Jan 2020.

The host server was turned off (almost the all time) so I do not think that Windows Update could cause this.

I'v found that `ServiceProcessInstaller` is hosted in the `System.ServiceProcess.dll` however there is no `System.ServiceProcess.dll` in the `dotnet publish  -r win10-x64` output folder.

**Comment by phatboyg** [comment] 2020-12-06 02:54
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

**Closed by phatboyg** 2020-12-06 02:54 UTC
