### ISSUE TITLE
Log4Net integration not working in Start() Stop() methods

### ISSUE THREAD

**Issue by mortan** [Topshelf/Topshelf#206] opened 2014-10-15 14:56 UTC
Hi!

I recently discovered that log.\* calls in our main service entry points don't produce any log entries. When the service is running everything seems to work.

I created a small gist to demonstrate it: https://gist.github.com/mortan/8055a959a74c4f2719f0

**Comment by josephdecock** [comment] 2015-12-14 22:17
I've observed similar behavior with the BeforeStartingService hook. What I observe is that this only happens when running as a service. When I run from the command line, I get the logging as expected.

Related stackoverflow question that I asked: http://stackoverflow.com/questions/34230156/unable-to-log-inside-topshelf-beforestartingservice-callback

**Comment by josephdecock** [comment] 2015-12-15 14:17
Some further investigation has found that this issue seems to be specific to the StartHost. I get logging if I run my service with the debugger, and I get logging if I install my service and then start it from Windows (using the Services gui). I only fail to get logging when I start the service from the command line.

Also, switching from log4net to nlog seems to be a workaround.

**Comment by danspam** [comment] 2016-01-21 00:39
I can second that there is a problem with log4net logging during startup when you start the service via the command line. Starting the service via the GUI seems to be ok.

**Comment by mortan** [comment] 2016-10-20 15:38
Any update on this? I just ran into the same issue again. After some time finding the cause why I don't see my Serilog log statements I searched on google and found my own bug report.

I can't really recommend using Topshelf anymore if this bug doesn't get fixed. Any exception that is thrown during the startup results in some cryptic System.ComponentModel.Win32Exception or TimeoutException, without the user having a chance to see the real cause.

**Comment by kvarv** [comment] 2017-07-03 08:26
When you run `myapp.exe start` you actually get two processes running. One instance from calling 'start' and one instance from the internal invocation of `sericeController.Start()`. Because of this you won't see the logged console output from the latter process. Now you might have expected to see output from the latter process in a log file. However, the former process takes a lock on the log file causing the latter to not being able to log. Adding `<lockingModel type="log4net.Appender.FileAppender+MinimalLock" />` to your file appender prevents the exclusive lock. Be aware that this has a drastic performance implication.

This is not a bug in Topshelf. I would recommend using powershell to start the service, ie `Get-Service -Name MyApp | Start-Server`. This also takes care of the problems described in #309.

**Comment by mbergdal** [comment] 2017-10-23 11:50
Thanks @kvarv. Ran into the same problem `Get-Service -Name MyApp | Start-Service` worked fine.

**Comment by snakefoot** [comment] 2018-06-22 23:05
Maybe something that will help others:

https://stackoverflow.com/questions/50746454/why-is-my-windows-service-not-logging-until-the-service-is-restarted

**Comment by phatboyg** [comment] 2020-12-06 03:00
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.

**Closed by phatboyg** 2020-12-06 03:00 UTC
