### ISSUE TITLE
VSTS start TopShelf service fails "Access Denied"

### ISSUE THREAD

**Issue by ygeelen-tb** [Topshelf/Topshelf#349] opened 2017-01-09 12:09 UTC
Using a Domain user that's member of the Administrator group of the target server, I've been able to Stop and Install a TopShelf service.
However the "Start Windows Service" release step keeps failing with the following error:
"The *** service terminated with the following error: 
Access is denied."
Event ID: 7023
Level: Error

Attempting to start the service from the commandline or through the Services mmc.exe results in the same error:

PS F:\***\winservice\deploy> .\***.exe start
Configuration Result:
[Success] Name ***
[Success] ServiceName ***
Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

I don't think this really is a permission issue, because the same Domain user had Full Control on the folder and *.exe file of the service.

We're running Windows Server 2008 R2 and the service is installed on the F partition (not C).

**Comment by ygeelen-tb** [comment] 2017-01-11 11:37
@TravisTheTechie Any idea what we are missing / doing wrong ?

**Comment by phatboyg** [comment] 2017-01-11 15:46
Enable some logging and try to find out why your service is crashing when Starting.

**Comment by KirillOFF** [comment] 2017-01-12 16:34
Such error may be caused by console logger, try to disable it

**Comment by TravisTheTechie** [comment] 2017-01-17 03:01
Whenever there is a permission error, it's almost always that there's a resource that a user doesn't have access to. A file on disk, a directory, or something else. Turning on logging sometimes helps, but sometimes it doesn't since initializing the logging is what's failing. It's hard to diagnose -- there are some tools that can help though: http://security.stackexchange.com/questions/6702/monitoring-file-access-on-windows

**Comment by TravisTheTechie** [comment] 2017-02-08 05:40
Closing unless until we get more info back.

**Closed by TravisTheTechie** 2017-02-08 05:40 UTC

**Comment by muziekklas** [comment] 2017-02-10 09:14
It is my task to resolve this issue.
Logging (using Log4Net) does not show anything. I think it doesn't even get into the code we wrote.
Allthough we got in the EventViewer on the executing machine following application error:

`Service cannot be started. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Unity.ConventionExtension.ConventionExtensionConfiguration.<>c.<Register>b__6_0(Assembly x)
   at System.Linq.Enumerable.<SelectManyIterator>d__16'2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator'1.MoveNext()
   at System.Collections.Generic.List'1..ctor(IEnumerable'1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable'1 source)
   at Unity.ConventionExtension.ConventionExtensionConfiguration.Register(Func'2 nameFunction, Func'2 defaultLifetimeManagerFunction)
   at Unity.ConventionExtension.ConventionExtensionConfiguration.Register(Func'2 nameFunction)
   at Unity.ConventionExtension.ConventionExtensionConfiguration.Register()`

The stacktrace ends there suddenly with 3 dots (...) so I cannot follow down the trace.
Just an assumption: could it be that the DLL's of our service are not loaded? If yes, Any clue how to overcome this?

**Comment by TravisTheTechie** [comment] 2017-02-11 16:08
At first glance I would think that yes, it fails to load the DLLs. Check permissions on disk for the service user vs. the installation user. Ensure the files aren't locked and unable to be opened. You could make sure [Shadow Copy](https://msdn.microsoft.com/en-us/library/ms404279(v=vs.110).aspx) is enabled if you think file locks are a contention.

**Comment by ygeelen-tb** [comment] 2017-02-13 15:26
@TravisTheTechie:
It seems that our IoC registrations were not working because we were not using the additional NuGet package TopShelf.Unity. Because of this our logging framework was not initialized and nothing was being logged.

It would have saved us a lot of time if there would be documentation about the various IoC NuGet packages similar to the documentation that exists for logging NuGet packages here: https://topshelf.readthedocs.io/en/latest/configuration/logging.html
